'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../maschera-ricette.html'),'utf8'),db=require('../db-ricette.json');
const elements={};
function element(group){
 const fields=Object.fromEntries(['campo-testo1','campo-testo2','campo-flag-mostra','campo-ruolo-vegetale','campo-fonte-quantita','campo-limite-quota','campo-composizioni','campo-cotture'].map(k=>[k,{value:'',style:{},innerHTML:'',textContent:''}]));
 return {dataset:{},fields,querySelector(s){return fields[s.slice(1)];},querySelectorAll(s){if(s==='.opzione-selettore')return [];if(s==='.ingr-check:checked')return (group.ingredienti||[]).map(i=>{const original=typeof i==='string'?{nome:i}:i;const r={dataset:{originale:encodeURIComponent(JSON.stringify(original))},querySelector:s=>s==='.campo-dose'?{value:original.dose??''}:null,querySelectorAll:()=>[]};return {dataset:{nome:original.nome,stack:String(original.stack??1),roll:String(original.roll??1)},closest:()=>r};});if(s==='.cottura-check:checked')return (group.cotture||[]).map(i=>({dataset:{nome:typeof i==='string'?i:i.nome,stack:String(i.stack??1),roll:String(i.roll??1)}}));if(s==='.campo-dose-composizione')return (group.composizioni||[]).flatMap((c,ci)=>c.ingredienti.map((i,ii)=>({dataset:{composizione:String(ci),ingrediente:String(ii)},value:i.dose??''})));return [];}};
}
const context={structuredClone,document:{getElementById:id=>elements[id]},condimentiSelezionatiCorrenti:()=>[],renderIngredientiGruppo:()=>{}};vm.createContext(context);
const a=html.indexOf('function doseRicettaDaCampo('),b=html.indexOf('function svuotaForm()',a);vm.runInContext('let VOCI=[];let INDICE_IN_MODIFICA=null;'+html.slice(a,b),context);
for(const recipe of db.ricette){for(const group of recipe.gruppi){elements.g=element(group);context.scriviGruppo('g',group);const read=context.leggiGruppo('g');assert.deepEqual(JSON.parse(JSON.stringify(read.ingredienti)),group.ingredienti,'ingredienti/dosi/metadati id '+recipe.id);if(group.composizioni)assert.deepEqual(JSON.parse(JSON.stringify(read.composizioni)),group.composizioni);if(group.quantita)assert.deepEqual(JSON.parse(JSON.stringify(read.quantita)),group.quantita);if(group.limite)assert.deepEqual(JSON.parse(JSON.stringify(read.limite)),group.limite);}}
const mixed=context.applicaQuotaGruppo({categoria:'PL',ruoli:['PL','S']},'G','nutrizionista');assert.deepEqual(Array.from(mixed.ruoli),['PL','G']);assert.equal(mixed.quantita.parametro,'quoteVegetali.G');assert.equal(mixed.limite.parametro,'quoteVegetali.G.massimo');
const specific=context.applicaDoseIngrediente({nome:'Pomodoro',ruoli:['S'],stack:0,roll:0},'60');assert.equal(specific.dose,60);assert.equal(specific.quantita.fonte,'ricetta');assert.equal(specific.stack,0);assert.equal(context.applicaDoseIngrediente(specific,'').dose,undefined);assert.equal(context.applicaDoseIngrediente(specific,'0').dose,0);
for(const v of ['-1','Infinity','abc'])assert.throws(()=>context.doseRicettaDaCampo(v));
const sugo=db.ricette.find(r=>r.id===43).gruppi[1];const garnish=context.applicaQuotaGruppo(sugo,'G','nutrizionista');assert.equal(garnish.composizioni[0].ingredienti[0].ruoli[0],'G');assert.equal(garnish.composizioni[0].ingredienti[0].dose,40);assert.equal(garnish.composizioni[0].copertura.ruoli[0],'G');
const recipe=db.ricette.find(r=>r.id===44);vm.runInContext('VOCI=[JSON.parse('+JSON.stringify(JSON.stringify(recipe))+')];INDICE_IN_MODIFICA=0;',context);
for(let i=0;i<4;i++){elements['gruppo'+(i+1)]=element(recipe.gruppi[i]);context.scriviGruppo('gruppo'+(i+1),recipe.gruppi[i]);}elements.campoStackScope={value:recipe.stackScope};const read=context.leggiFormCorrente();assert.deepEqual(JSON.parse(JSON.stringify(read.copertura)),recipe.copertura);assert.equal(read.id,44);
assert(html.includes('campo-dose-composizione'));assert(html.includes('campo-ruolo-vegetale'));assert(html.includes("ghSave('db-ricette.json'"));
console.log('PASS: maschera conserva dosi/metadati dei 39 modelli e composizioni, legge S/G e fonti/massimi, modifica dose/zero/vuoto, rifiuta invalidi e conserva copertura proteica congiunta. Nessuna scrittura GitHub.');
