'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const stores={};
for(const name of ['ingredienti','varianti','ricette','impostazioni','piano','consumoGiorno','inventario','diagnosticaCopertura'])stores[name]=new Map();
global.getAll=async n=>[...stores[n].values()].map(x=>structuredClone(x));
global.getOne=async(n,k)=>structuredClone(stores[n].get(k));
global.put=async(n,x)=>stores[n].set(x.id??x.chiave,structuredClone(x));
global.delKey=async(n,k)=>stores[n].delete(k);
global.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(__dirname,'..',String(url).split('?')[0]),'utf8'))});
const N=require('../nutrition-config.js');require('../motor-v12.js');const M=global.DietaPlannerMotorV12;
(async()=>{
 const defaults=N.resolveNutritionConfig({});assert.deepEqual(defaults.quoteVegetali,{S:{quantita:null,massimo:null},G:{quantita:null,massimo:null}});
 for(const quote of [{quantita:-1},{massimo:-1},{quantita:2,massimo:1}])assert.equal(N.resolveNutritionConfig({nutritionist:{config:{quoteVegetali:{S:quote}}}}).valid,false);
 await M.inizializza({basePath:''});
 const modelDb=JSON.parse(fs.readFileSync(path.join(__dirname,'../db-ricette.json'),'utf8'));
 const originalTemplates=JSON.stringify(modelDb);
 assert.equal(M.getRicette().find(r=>r.recipeModelId===44).S,60,'dose specifica preservata senza default generico');
 const sauces=M.getRicette().filter(r=>r.recipeModelId===43);
 assert(sauces.some(r=>r.S===70));assert(sauces.some(r=>r.S===80));
 const missing=M.getRicette().find(r=>r.recipeModelId===6);
 assert(missing.ingredienti.find(i=>i.nome==='Pomodoro fresco').doseMancante);
 assert.equal(missing.quoteVegetaliComplete,false,'zero diagnostico non significa sugo assente');
 const config={quoteVegetali:{S:{quantita:61,massimo:85},G:{quantita:31,massimo:45}}};
 await put('impostazioni',{chiave:'configAvanzata',valore:config});
 await M.aggiornaCacheDosiRicette();
 const recipes=await getAll('ricette');assert(recipes.every(r=>typeof r.S==='number'&&typeof r.G==='number'));
 const tomato=recipes.filter(r=>r.recipeModelId===6);assert.equal(tomato.length,3);
 for(const r of tomato){assert.equal(r.S,61);assert.equal(r.G,0);assert.equal(r.quoteVegetaliComplete,true);}
 assert.equal(recipes.find(r=>r.recipeModelId===31).G,31);
 const combined=recipes.find(r=>r.recipeModelId===44);assert.equal(combined.S,60,'dose già dichiarata preservata');
 assert.deepEqual(combined.coperturaDichiarata.proteine,[{tipo:'congiunta',ruoli:['PU','PL']}]);
 const cold=recipes.find(r=>r.recipeModelId===10);assert.equal(cold.S,0);assert.equal(cold.G,0);assert(M.copertura(cold).V,'piatto unico con V completa');
 const mixed=recipes.find(r=>r.recipeModelId===43&&r.ingredienti.filter(i=>i.ruoli?.includes('S')).length===2);
 assert.equal(mixed.S,80,'composizione fissa con due dosi vegetali');
 const real=M.snapshotRealizzazione({ricettaId:tomato[0].id},tomato[0]),frozen=JSON.stringify(real);
 await put('piano',{id:'2026-09-28_pranzo',realizzazioni:[real]});
 await put('consumoGiorno',{id:'preserved',realizzazioni:[real]});
 const saved=JSON.stringify(await getAll('piano')),consumed=JSON.stringify(await getAll('consumoGiorno'));
 config.quoteVegetali.S.quantita=53;config.quoteVegetali.S.massimo=55;
 await put('impostazioni',{chiave:'configAvanzata',valore:config});await M.aggiornaCacheDosiRicette();
 assert.equal(M.getRicetta(tomato[0].id).S,53);
 assert.equal((await M.materializzaRealizzazione(real)).S,61,'snapshot salvato non riscritto');
 assert.equal(JSON.stringify(real),frozen);assert.equal(JSON.stringify(await getAll('piano')),saved);assert.equal(JSON.stringify(await getAll('consumoGiorno')),consumed);
 assert.equal(await M.ricettaAmmessa(M.getRicetta(combined.id),'2026-09-28',{ignoraCooldown:true}),false,'dose dichiarata oltre cap non ridotta di nascosto');
 const zeroRecipe={...tomato[0],ingredienti:tomato[0].ingredienti.map(i=>i.ruoli?.includes('S')?{...i,grammi:0,quantita:0}:i)};assert.equal(await M.ricettaAmmessa(zeroRecipe,'2026-09-28',{runtimeConfig:{resolved:N.resolveNutritionConfig({nutritionist:{config:{quoteVegetali:{S:{quantita:0,massimo:0}}}}})}}),false,'zero non propone un piatto con sugo nominale assente');
 const model=structuredClone(modelDb.ricette.find(r=>r.id===44));model.id='fixture-frittata';model.classe=['PU','PL','V'];model.copertura={ruoli:model.classe,proteine:[{tipo:'congiunta',ruoli:['PU','PL']}]};
 model.gruppi=model.gruppi.filter(g=>g.categoria==='PU'||g.categoria==='PL');
 const peas=model.gruppi.find(g=>g.categoria==='PL');peas.ruoli=['PL','V'];peas.limite=null;
 const frittata=await M.compilaRicetta(model,M.generaCombinazioni(model)[0],0);
 assert.equal(frittata.S,0);assert.equal(frittata.G,0);assert(M.copertura(frittata).P&&M.copertura(frittata).V);
 assert.equal(M.coperturaVerduraRicette([frittata],{vegetablePortionGrams:200,saladPortionGrams:70}).grammiRealiPerRuolo.V,60,'piselli proteici e vegetali senza trasformarli in G');
 assert.equal(JSON.stringify(modelDb),originalTemplates,'modelli non mutati durante compilazione');
 const override=M.applicaOverrideQuantitaRealizzazione(tomato[0],{ingredientiEffettivi:[{...tomato[0].ingredienti.find(i=>i.nome==='Pomodoro fresco'),quantita:42,grammi:42,overrideQuantita:'fixture'}]});assert.equal(override.S,42);
 const invalid=structuredClone(model);invalid.gruppi[0].ruoli=['V','S'];await assert.rejects(()=>M.compilaRicetta(invalid,M.generaCombinazioni(invalid)[0],0),/ambiguo/);
 config.quoteVegetali.S.quantita=49;await put('impostazioni',{chiave:'configAvanzata',valore:config});M.invalidaConfigRuntime();await M.inizializza({basePath:''});assert.equal((await getOne('ricette',tomato[0].id)).S,49,'configurazione diversa invalida cache al riavvio');
 assert.equal(JSON.stringify(await getAll('piano')),saved);assert.equal(JSON.stringify(await getAll('consumoGiorno')),consumed);
 const source=fs.readFileSync(path.join(__dirname,'../motor-v12.js'),'utf8');
 const metas=source.split('/* @qa-metadata').slice(1).map(part=>JSON.parse(part.split('*/')[0]));assert(metas.some(m=>m.id==='P1-modelli-quote-vegetali'));
 console.log('PASS: modelli dichiarativi, esploso S/G, Set/cap distinti, composizioni e piatti unici, fixture frittata, override e snapshot. Cataloghi/funzioni reali, archivio in memoria; nessuna ricetta/dose fixture salvata nel catalogo.');
})().catch(e=>{console.error(e);process.exitCode=1;});
