'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const stores={};
for(const name of ['ingredienti','varianti','ricette','impostazioni','piano','consumoGiorno','inventario','diagnosticaCopertura'])stores[name]=new Map();
global.getAll=async n=>[...stores[n].values()].map(x=>structuredClone(x));
global.getOne=async(n,k)=>structuredClone(stores[n].get(k));
global.put=async(n,x)=>stores[n].set(x.id??x.chiave,structuredClone(x));
global.delKey=async(n,k)=>stores[n].delete(k);
global.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(__dirname,'..',String(url).split('?')[0]),'utf8'))});
require('../motor-v12.js');const M=global.DietaPlannerMotorV12;
(async()=>{
 await M.inizializza({basePath:''});
 const before=JSON.stringify(await getAll('ricette'));
 const pool=await M.poolAmmesso('2026-09-28');
 const recipe=pool.find(r=>r.slot?.some(s=>s.ingrediente?.nome&&s.ingrediente.dose==null&&r.ingredienti.some(i=>i.nome===s.ingrediente.nome&&/^P/.test(i.categoria)&&i.quantita>0)));
 assert(recipe,'serve una ricetta reale con proteina senza dose eccezionale');
 const ing=recipe.ingredienti.find(i=>/^P/.test(i.categoria));
 const old=M.snapshotRealizzazione({ricettaId:recipe.id},recipe),frozen=JSON.stringify(old);
 await put('impostazioni',{chiave:'vincoliIngredientiNutrizionista',valore:{[ing.ingredienteId]:{contesti:{pastoPrincipale:{quantita:137}}}}});
 M.invalidaConfigRuntime();
 const fresh=(await M.poolAmmesso('2026-09-28')).find(r=>r.id===recipe.id);assert(fresh);
 assert.equal(fresh.ingredienti.find(i=>i.nome===ing.nome).quantita,137);
 assert.notEqual(fresh.nutrienti.kcal,recipe.nutrienti.kcal);
 const past=await M.materializzaRealizzazione(old);
 assert.equal(past.ingredienti.find(i=>i.nome===ing.nome).quantita,ing.quantita);
 assert.equal(JSON.stringify(old),frozen,'snapshot preesistente immutato');
 assert.equal(JSON.stringify(await getAll('ricette')),before,'cache persistente e catalogo immutati');
 console.log('PASS: nuova dose nel pool reale, nutrienti aggiornati, snapshot precedente e cache persistente preservati. Archivio simulato.');
})().catch(e=>{console.error(e);process.exitCode=1;});
