'use strict';
const assert=require('node:assert/strict');
const K=require('../pwa-contracts.js'),B=require('../barcode-spesa.js');
const recipe=(name,cat,cooking='lessato')=>({id:name,ingredienti:[{nome:name,ingredienteId:name,categoria:cat,allergeni:[]}],slot:[{cottura:{nome:cooking}}]});
const tofu=recipe('tofu','PL'),ceci=recipe('ceci','PL'),riso=recipe('riso','C'),v=recipe('carote','V');
const history=[{...K.identity(tofu),date:'2026-09-01',slot:'2026-09-01_pranzo'},{...K.identity(riso),date:'2026-09-01',slot:'2026-09-01_pranzo'}];
assert.equal(K.availability(tofu,'2026-09-15',history).stack,0);
assert.equal(K.availability(tofu,'2026-09-16',history).stack,1);
assert.deepEqual(K.filter([tofu,ceci,riso,v],'2026-09-15',history,['C']),[ceci,riso,v],'esaurimento C non riapre tofu');
assert.equal(K.hardReason(recipe('tofu','PL','arrosto'),'2026-09-02',history),'proteina_consecutiva');
assert.equal(K.filter([tofu],'2026-09-03',history,true).length,0,'reset non riapre duplicati settimanali');
assert.equal(K.identity(v).rotationKeys.length,0);
const regular={componenti:{proteine:'latte',carboidrati:'pane'}};
assert.equal(K.nextBreakfastCount(6,regular),7);assert.equal(K.nextBreakfastCount(7,regular),0);
assert.equal(K.nextBreakfastCount(4,{componenti:{}}),0);
const stock=[{id:'secondo',variantId:'riso',stato:'disponibile',quantita:100,dataScadenza:'2026-10-01'},{id:'primo',variantId:'riso',stato:'disponibile',quantita:30,dataScadenza:'2026-09-25'}];
const used=K.consumeInventory(stock,[{variantId:'riso',quantita:50},{variantId:'sale',quantita:5,nonRichiedeInventario:true}],'2026-09-23');
assert.equal(used.changed.find(x=>x.id==='primo').quantita,0);assert.equal(used.changed.find(x=>x.id==='secondo').quantita,80);assert.equal(stock[1].quantita,30);assert.equal(used.missing.length,0);
assert.throws(()=>K.consumeInventory(stock,[{variantId:'riso',unita:'pz',quantita:2}],'2026-09-23'),/conversione/);
assert(B.validEAN('4006381333931'));assert(!B.validEAN('4006381333932'));
assert.equal(B.quantity({id:'4006381333931',variantId:'riso',quantita:500,unita:'g'},2,{id:'riso'}),1000);
console.log('PASS contratti: soglia 15 giorni, reset C/P separato, duplicati, consecutività, colazione, FEFO, conversioni ed EAN.');
