/* DietaPlanner — motore unico v79. Dipende da engine-core.js. */
(function(global){
'use strict';
const E=global.DietaPlannerEngine;
const N=global.DietaPlannerNutritionConfig;
if(!E)throw new Error('DietaPlannerEngine non caricato');
if(!N)throw new Error('DietaPlannerNutritionConfig non caricato');
let ULTIMA_CONFIG_NUTRIZIONALE=N.resolveNutritionConfig({});
const FREQUENZE_MOTORE_BIBBIA=E.DEFAULTS.proteinFrequencies;
const CAP_SOTTOTIPI_MOTORE=E.DEFAULTS.subtypeCaps;
const SOTTOTIPI_MOTORE={carne:['carne_bianca','carne_rossa','affettati'],pesce:['pesce_bianco','pesce_azzurro','pesce_grande','crostacei','molluschi','pesce_conservato'],formaggi:['formaggio_fresco','formaggio_stagionato'],uova:['uova'],legumi:['legumi']};
const COTTURE_PER_PROTEINA_V10={carne_bianca:['alla piastra','al vapore','al limone','al forno'],carne_rossa:['alla piastra','al limone','al forno','in umido'],affettati:['al naturale'],pesce_bianco:['alla piastra','al vapore','al limone','al forno'],pesce_azzurro:['alla piastra','al vapore','al limone','al forno'],pesce_grande:['alla piastra','al vapore','al limone','al forno'],pesce_conservato:['al naturale'],crostacei:['alla piastra','al vapore','al limone'],molluschi:['alla piastra','al vapore','al limone'],formaggio_fresco:['al naturale'],formaggio_stagionato:['al naturale'],uova:['strapazzate','sode','in frittata'],legumi:['al naturale','in umido']};
const COTTURE_STANDARD=COTTURE_PER_PROTEINA_V10;
function motoreMescola(a){return E.shuffle(a);}
function motoreCategoriaDiSottotipo(s){return E.macroOf(s);}
function scegliMenoRecenteMotore(c,getTs,getUse){const last={},use={};for(const x of c||[]){const k=typeof x==='string'?x:x.id;last[k]=getTs?getTs(x):0;use[k]=getUse?getUse(x):0;}return E.oldest(c,last,use);}
function costruisciGrigliaBase(giorni,tabella){const r=E.buildProteinGrid(giorni,tabella||{},null,{},Math.random),celle={};for(const g of giorni){celle[g]={};for(const p of ['pranzo','cena'])celle[g][p]={gruppoProteicoLargo:r.cells[g][p].macro,origine:r.cells[g][p].source==='user'?'utente':'motore',stato:'definita'};}return {celle,errori:r.errors,conteggi:r.counts};}
function adattaConfigProfilo(config,tabella){
  const resolved=N.resolveNutritionConfig({nutritionist:{config:config||{}}}),forbidden=new Set(resolved.profile.forbiddenProteinMacros||[]),proteinFrequencies={};
  for(const [macro,lim] of Object.entries(resolved.proteinFrequencies||{}))proteinFrequencies[macro]=forbidden.has(macro)?{min:0,max:0,target:0,quantita:lim.quantita}:Object.assign({},lim);
  const clean={};for(const [day,items] of Object.entries(tabella||{}))clean[day]=(items||[]).filter(x=>!forbidden.has(x));
  return {cfg:{proteinFrequencies},tabella:clean,resolved};
}
async function costruisciGrigliaConfigurata(giorni,tabella,storico,resolved){
  resolved=resolved||await caricaConfigurazioneNutrizionaleRisolta();
  const forbidden=new Set(resolved.profile&&resolved.profile.forbiddenProteinMacros||[]),proteinFrequencies={};
  for(const [macro,lim] of Object.entries(resolved.proteinFrequencies||{}))proteinFrequencies[macro]=forbidden.has(macro)?{min:0,max:0,target:0,quantita:lim.quantita}:Object.assign({},lim);
  const clean={};for(const [day,items] of Object.entries(tabella||{}))clean[day]=(items||[]).filter(x=>!forbidden.has(x));
  const r=E.buildProteinGrid(giorni,clean,{proteinFrequencies},{lastMacro:storico&&storico.ultimoCategoriaProteica||{}},Math.random),celle={};
  for(const g of giorni){celle[g]={};for(const p of ['pranzo','cena'])celle[g][p]={gruppoProteicoLargo:r.cells[g][p].macro,origine:r.cells[g][p].source==='user'?'utente':'motore',stato:'definita'};}
  return {celle,errori:r.errors,conteggi:r.counts};
}
function validaGrigliaBase(celle){let totale=0,piene=0;const vuote=[],conteggiPerCategoria={};for(const g of Object.keys(celle||{}))for(const p of ['pranzo','cena']){totale++;const c=celle[g][p]&&celle[g][p].gruppoProteicoLargo;if(c){piene++;conteggiPerCategoria[c]=(conteggiPerCategoria[c]||0)+1;}else vuote.push(g+'_'+p);}return {piene,totale,vuote,completa:!vuote.length,conteggiPerCategoria};}
function risolviSottotipoFine(macro,consumi){const pool=SOTTOTIPI_MOTORE[macro]||[macro],caps=ULTIMA_CONFIG_NUTRIZIONALE&&ULTIMA_CONFIG_NUTRIZIONALE.subtypeCaps||CAP_SOTTOTIPI_MOTORE,allowed=pool.filter(s=>caps[s]===undefined||(consumi&&consumi[s]||0)<caps[s]);return allowed.length?E.oldest(allowed,{},consumi||{}):null;}
async function profiloSicurezza(){const [a,b,c]=await Promise.all([getOne('impostazioni','allergeniAttivi'),getOne('impostazioni','ingredientiBloccati'),getOne('impostazioni','configAvanzata')]);return {allergeni:a&&a.valore||[],bloccati:b&&b.valore||[],profilo:c&&c.valore&&c.valore.dietProfile||'onnivoro'};}
function costruisciMappaVarianti(varianti,basi,jsonMap){const b=new Map((basi||[]).map(x=>[x.id,x]));return new Map((varianti||[]).map(v=>[v.id,{variant:v,base:b.get(v.ingredienteId)||null,json:jsonMap&&jsonMap[v.nome]||null}]));}
function poolDelGiorno(i){return i<=2?'fresco':i<=4?'fresco_duraturo':'confezionato';}
function contorniAmmessiPerPool(contorni,mappa,pool){return (contorni||[]).filter(r=>{const ing=(r.ingredienti||[]).find(x=>x.variantId),x=ing&&mappa.get(ing.variantId);return !x||E.vegetableTier(Object.assign({},x.variant,x.base))===pool;});}
async function calcolaPoolVerdureGiornaliero(giorno){return poolDelGiorno((new Date(giorno+'T12:00:00').getDay()+6)%7);}
async function costruisciStoricoConsumatiMotore(){const [log,recipes,vars,bases]=await Promise.all([getAll('consumoGiorno'),getAll('ricette'),getAll('varianti'),getAll('ingredienti')]);const rBy=new Map(recipes.map(r=>[r.id,r])),vBy=new Map(vars.map(v=>[v.id,v])),bBy=new Map(bases.map(b=>[b.id,b]));const out={ultimoRicetta:{},ultimoCarb:{},ultimoVerdura:{},sottotipiTotali:{},ultimoSottotipo:{},ultimoCategoriaProteica:{}};for(const rec of log||[]){const ts=Date.parse((rec.giorno||'')+'T12:00:00')||0;if(rec.primoCereale)out.ultimoCarb[rec.primoCereale]=Math.max(out.ultimoCarb[rec.primoCereale]||0,ts);for(const id of rec.ricettaIds||[]){const r=rBy.get(id);if(!r||r.piattoSpeciale)continue;out.ultimoRicetta[id]=Math.max(out.ultimoRicetta[id]||0,ts);if(r.gruppoProteico){out.sottotipiTotali[r.gruppoProteico]=(out.sottotipiTotali[r.gruppoProteico]||0)+1;out.ultimoSottotipo[r.gruppoProteico]=Math.max(out.ultimoSottotipo[r.gruppoProteico]||0,ts);const m=motoreCategoriaDiSottotipo(r.gruppoProteico);out.ultimoCategoriaProteica[m]=Math.max(out.ultimoCategoriaProteica[m]||0,ts);}for(const ing of r.ingredienti||[]){const v=vBy.get(ing.variantId),base=v&&bBy.get(v.ingredienteId);if(base&&base.gruppo==='verdura')out.ultimoVerdura[v.id]=Math.max(out.ultimoVerdura[v.id]||0,ts);}}}return out;}
async function filtriSicurezzaRicette(automatico){const [vars,bases,safe]=await Promise.all([getAll('varianti'),getAll('ingredienti'),profiloSicurezza()]);const bBy=new Map(bases.map(x=>[x.id,x])),blockedBase=new Set(safe.bloccati),blockedVariants=vars.filter(v=>blockedBase.has(v.ingredienteId)).map(v=>v.id),meta={};for(const v of vars){const b=bBy.get(v.ingredienteId)||{};meta[v.id]={baseId:v.ingredienteId,gruppo:b.gruppo,allergeni:b.allergeni||[],bloccoManuale:false};}return {automatic:automatico,activeAllergens:safe.allergeni,blockedIngredientIds:blockedVariants,ingredientMeta:meta};}
async function ricetteAmmesse(automatico){
  const [all,ctx,safe,nonGraditi]=await Promise.all([getAll('ricette'),filtriSicurezzaRicette(automatico),profiloSicurezza(),getOne('impostazioni','cerealiNonGraditi')]);
  const cerealiOff=new Set(nonGraditi&&nonGraditi.valore||[]);
  const esclusi=safe.profilo==='vegetariano'
    ? new Set(['carne','pesce'])
    : safe.profilo==='vegano'
      ? new Set(['carne','pesce','formaggi','uova'])
      : new Set();
  return all.filter(r=>{
    if(E.recipeBlocked(r,ctx))return false;
    if(automatico&&(r.ingredienti||[]).some(i=>cerealiOff.has(ctx.ingredientMeta[i.variantId]&&ctx.ingredientMeta[i.variantId].baseId)))return false;
    if(esclusi.has(motoreCategoriaDiSottotipo(r.gruppoProteico)))return false;
    if(safe.profilo==='vegano'&&(r.ingredienti||[]).some(i=>{
      const m=ctx.ingredientMeta[i.variantId]||{};
      return (m.allergeni||[]).some(a=>['latte','uova','pesce','crostacei','molluschi'].includes(a));
    }))return false;
    return true;
  });
}
async function filtraContorniPerVerdureAttive(contorni){const [r,legacy]=await Promise.all([getOne('impostazioni','setVerdureDisattivate'),getOne('impostazioni','verdureDisattivate')]),off=new Set(r&&r.valore!==undefined?r.valore:(legacy&&legacy.valore||[]));return (contorni||[]).filter(x=>!(x.ingredienti||[]).some(i=>off.has(i.variantId)));}
function estraiSelezioneCarboidratiUtente(config,origini,stati,explicitZeroKeys){
  config=config||{};origini=origini||{};stati=stati||{};const counts={},hasOrigins=Object.values(origini).some(v=>Array.isArray(v)&&v.length);
  for(const [key,value] of Object.entries(config)){
    const n=Number(value)||0;
    if(hasOrigins){const userCount=(origini[key]||[]).filter(x=>x==='utente').length;if(userCount>0)counts[key]=userCount;}
    else if(n>0)counts[key]=n;
  }
  return {counts,states:stati,explicitZeroKeys:Array.isArray(explicitZeroKeys)?explicitZeroKeys:[]};
}
async function caricaConfigurazioneNutrizionaleRisolta(){
  const keys=['configAvanzata','vincoliIngredientiNutrizionista','allergeniAttivi','ingredientiBloccati','tettiIngredienteSettimanali','configCarboidrati','configCarboidratiOrigini','configCarboidratiStati','configCarboidratiExplicitZeroKeys'];
  const rows=await Promise.all(keys.map(k=>getOne('impostazioni',k))),by={};keys.forEach((k,i)=>by[k]=rows[i]&&rows[i].valore);
  const carbohydrates=estraiSelezioneCarboidratiUtente(by.configCarboidrati,by.configCarboidratiOrigini,by.configCarboidratiStati,by.configCarboidratiExplicitZeroKeys);
  const resolved=N.resolveNutritionConfig({
    nutritionist:{config:by.configAvanzata||{},ingredientConstraints:by.vincoliIngredientiNutrizionista||{},allergens:by.allergeniAttivi||[],blockedIngredientIds:by.ingredientiBloccati||[]},
    user:{carbohydrates,ingredientWeeklyCaps:by.tettiIngredienteSettimanali||{}}
  });
  ULTIMA_CONFIG_NUTRIZIONALE=resolved;return resolved;
}
function preparaBudgetCarboidratiMotore(resolved){
  resolved=resolved||ULTIMA_CONFIG_NUTRIZIONALE||N.resolveNutritionConfig({});const plan=resolved.carbohydrates||{},config=Object.assign({},plan.fixedCounts||{}),errori=[];
  let restanti=Number(plan.remainingSlots)||0,guardia=500;
  while(restanti>0&&guardia-->0){
    const pool=(plan.autoEligibleKeys||[]).filter(k=>(config[k]||0)<N.APP_DEFAULTS.carbCellMax);
    if(!pool.length){errori.push('Carboidrati: impossibile completare '+restanti+' slot senza violare esclusioni o tetti.');break;}
    const k=E.shuffle(pool,Math.random)[0];config[k]=(config[k]||0)+1;restanti--;
  }
  return {config,residuo:Object.assign({},config),errori,piano:plan};
}
function famiglieLimitateRicetta(r,limitedSubtypeByVariant,subtypeCaps){
  const out=new Set();if(!r)return out;
  if(subtypeCaps&&subtypeCaps[r.gruppoProteico]!==undefined)out.add(r.gruppoProteico);
  for(const ing of r.ingredienti||[]){const subtype=limitedSubtypeByVariant[ing.variantId];if(subtype&&subtypeCaps&&subtypeCaps[subtype]!==undefined)out.add(subtype);}
  return out;
}
function segnaFamiglieLimitatePasto(recipes,state){
  const found=new Set();for(const r of recipes||[])for(const subtype of famiglieLimitateRicetta(r,state.limitedSubtypeByVariant||{},state.nutritionConfig&&state.nutritionConfig.subtypeCaps||{}))found.add(subtype);
  for(const subtype of found)state.subtypeWeeklyCounts[subtype]=(state.subtypeWeeklyCounts[subtype]||0)+1;
}
function costruisciConteggiVincoliSettimana(giorni,includeAllPlanned,log,piano,recipes,limitedSubtypeByVariant,subtypeCaps){
  const daySet=new Set(giorni||[]),rBy=new Map((recipes||[]).map(r=>[r.id,r])),ingredientCounts={},subtypeCounts={},seenSlots=new Set();
  const addSlot=(slotKey,ids)=>{if(seenSlots.has(slotKey))return;seenSlots.add(slotKey);const found=new Set();for(const id of new Set(ids||[])){const r=rBy.get(id);if(!r)continue;E.accumulateRecipeIngredients(r,ingredientCounts);for(const st of famiglieLimitateRicetta(r,limitedSubtypeByVariant,subtypeCaps))found.add(st);}for(const st of found)subtypeCounts[st]=(subtypeCounts[st]||0)+1;};
  for(const rec of log||[]){if(!daySet.has(rec.giorno))continue;addSlot(rec.giorno+'_'+(rec.pasto||''),rec.ricettaIds||[]);}
  for(const voce of piano||[]){const sep=String(voce.id||'').lastIndexOf('_'),giorno=sep>=0?voce.id.slice(0,sep):'',pasto=sep>=0?voce.id.slice(sep+1):'';if(!daySet.has(giorno))continue;if(!(voce.consumato||voce.bloccata||includeAllPlanned))continue;const ids=voce.modo==='multi'?[...new Set((voce.realizzazioni&&voce.realizzazioni.length?voce.realizzazioni.map(x=>x.ricettaId):[voce.primoId,voce.secondoId,voce.contornoId]).filter(Boolean))]:[voce.ricettaId].filter(Boolean);addSlot(giorno+'_'+pasto,ids);}
  return {ingredientCounts,subtypeCounts};
}
async function creaStatoMotoreSettimana(giorniTarget,opzioni){
  const giorni=(giorniTarget&&giorniTarget.length)?giorniTarget:(typeof giorniSettimana==='function'?giorniSettimana(0):[]),includeAllPlanned=opzioni&&opzioni.includeAllPlanned!==undefined?!!opzioni.includeAllPlanned:true;
  const [storico,resolved,vars,bases,inv,log,piano,recipes]=await Promise.all([costruisciStoricoConsumatiMotore(),caricaConfigurazioneNutrizionaleRisolta(),getAll('varianti'),getAll('ingredienti'),getAll('inventario'),getAll('consumoGiorno'),getAll('piano'),getAll('ricette')]),budget=preparaBudgetCarboidratiMotore(resolved),caps={},mins={},inventoryByVariant={},baseBy=new Map(bases.map(b=>[b.id,b])),limitedSubtypeByVariant={};
  for(const v of vars){const rule=resolved.ingredientConstraints&&resolved.ingredientConstraints[v.ingredienteId];if(rule){if(rule.max!==null&&rule.max!==undefined)caps[v.id]=Number(rule.max);if(rule.min!==null&&rule.min!==undefined)mins[v.id]=Number(rule.min);}const base=baseBy.get(v.ingredienteId);if(base&&resolved.subtypeCaps&&resolved.subtypeCaps[base.sottotipo]!==undefined)limitedSubtypeByVariant[v.id]=base.sottotipo;}
  for(const row of inv||[])(inventoryByVariant[row.variantId]||(inventoryByVariant[row.variantId]=[])).push(row);
  const existing=costruisciConteggiVincoliSettimana(giorni,includeAllPlanned,log,piano,recipes,limitedSubtypeByVariant,resolved.subtypeCaps),nutritionErrors=[...(resolved.errors||[]),...(budget.errori||[])];
  return {storico,nutritionConfig:resolved,nutritionErrors,ricetteUsateGenerazione:new Set(),ingredientiUsatiGenerazione:new Set(),preferiteVerdureUsate:new Set(),carboidratiUsati:{},budgetCarb:budget,carbRemaining:Object.assign({},budget.residuo),carbsUsed:{},recipesUsed:new Set(),ingredientWeeklyCounts:Object.assign({},existing.ingredientCounts),ingredientCaps:caps,ingredientMins:mins,subtypeWeeklyCounts:Object.assign({},existing.subtypeCounts),limitedSubtypeByVariant,inventoryByVariant,vegetablesUsedWeek:{},vegetablesUsedDay:new Set(),history:{lastRecipe:storico.ultimoRicetta,lastCarb:storico.ultimoCarb,lastVegetable:storico.ultimoVerdura,lastMacro:storico.ultimoCategoriaProteica}};
}
function applicaTettiIngredienti(pool,state){const r=E.applyIngredientCaps(pool,state.ingredientWeeklyCounts,state.ingredientCaps);if(r.blockedAll)state.sforamenti=(state.sforamenti||[]).concat('tetto ingrediente: pool esaurito');const unmet=new Set(Object.keys(state.ingredientMins||{}).filter(id=>(state.ingredientWeeklyCounts[id]||0)<state.ingredientMins[id])),prioritarie=r.pool.filter(x=>(x.ingredienti||[]).some(i=>unmet.has(i.variantId)));return prioritarie.length?prioritarie:r.pool;}
function segnaIngredientiRicetta(r,state){if(r)E.accumulateRecipeIngredients(r,state.ingredientWeeklyCounts);return r;}
async function caricaPreferenzeMotoreDaSet(scarto){const giorni=giorniSettimana(scarto||0),[tab,lim,time,pref,off,offLegacy,recV,recP]=await Promise.all(['tabellaGiornoCategoria','setProteineLimitate','setPocoTempo','setVerdurePreferite','setVerdureDisattivate','verdureDisattivate','verduraRicorrente','verduraRicorrentePasti'].map(k=>getOne('impostazioni',k)));const giornoCategoria={},raw=tab&&tab.valore||{};giorni.forEach((g,i)=>{if(raw['giorno_'+i]&&raw['giorno_'+i].length)giornoCategoria[g]=raw['giorno_'+i].slice();});const vars=await getAll('varianti'),names=new Set(pref&&pref.valore||[]),offValue=off&&off.valore!==undefined?off.valore:(offLegacy&&offLegacy.valore||[]);return {giornoCategoria,proteineLimitate:lim&&lim.valore||[],pocoTempoPranzo:!!(time&&time.valore&&time.valore.pranzo),pocoTempoCena:!!(time&&time.valore&&time.valore.cena),verdurePreferiteVariantIds:vars.filter(v=>names.has(v.nome)).map(v=>v.id),verdureDisattivate:offValue||[],verduraRicorrenteVariantId:recV&&recV.valore||null,verduraRicorrentePasti:recP&&recP.valore||[]};}
async function scegliSottotipoMotore(macro,state){const all=await ricetteAmmesse(true),caps=state&&state.nutritionConfig&&state.nutritionConfig.subtypeCaps||CAP_SOTTOTIPI_MOTORE,counts=state.subtypeWeeklyCounts||{};let pool=(SOTTOTIPI_MOTORE[macro]||[macro]).filter(s=>all.some(r=>r.gruppoProteico===s&&['secondo','unico','modulare'].includes(r.tipoPortata||'unico')));pool=pool.filter(s=>caps[s]===undefined||(counts[s]||0)<caps[s]);return pool.length?scegliMenoRecenteMotore(pool,s=>state.storico.ultimoSottotipo[s]||0,s=>counts[s]||0):null;}
async function scegliProteinaModulareMotore(subtype,state,exclude){const all=await ricetteAmmesse(true);let pool=all.filter(r=>r.id!==exclude&&r.gruppoProteico===subtype&&!r.piattoSpeciale&&((r.tipoPortata==='modulare'&&r.sottoCategoriaModulare==='proteina')||r.tipoPortata==='secondo'));if(!pool.length)pool=all.filter(r=>r.id!==exclude&&r.gruppoProteico===subtype&&!r.piattoSpeciale&&(r.tipoPortata||'unico')==='unico'&&!E.parseCoverage(r).carb);return segnaIngredientiRicetta(E.chooseRecipe(applicaTettiIngredienti(pool,state),state,{automatic:true,inventoryByVariant:state.inventoryByVariant}),state);}
async function scegliSugoMotore(state,exclude){const all=await ricetteAmmesse(true),pool=all.filter(r=>r.id!==exclude&&r.tipoPortata==='modulare'&&(r.sottoCategoriaModulare||'sugo')==='sugo');return segnaIngredientiRicetta(E.chooseRecipe(applicaTettiIngredienti(pool,state),state,{automatic:true,inventoryByVariant:state.inventoryByVariant}),state);}
async function cercaComponentiModulari(tipo){const all=await ricetteAmmesse(true);return all.filter(r=>r.tipoPortata==='modulare'&&(r.sottoCategoriaModulare||'sugo')===tipo);}
function infoVerdura(r,vBy,bBy,qty){for(const ing of r.ingredienti||[]){const v=vBy.get(ing.variantId),b=v&&bBy.get(v.ingredienteId);if(b&&b.gruppo==='verdura')return {id:r.id,recipe:r,variantId:v.id,name:v.nome,meta:Object.assign({},v,b),quantity:qty[v.id]||0,portion:/insalata/i.test(v.nome)?70:200};}return null;}
async function scegliContornoMotore(giorno,state,pref,exclude){const [all,vars,bases,inv]=await Promise.all([ricetteAmmesse(true),getAll('varianti'),getAll('ingredienti'),getAll('inventario')]);const vBy=new Map(vars.map(v=>[v.id,v])),bBy=new Map(bases.map(b=>[b.id,b])),qty={};for(const x of inv)if(x.stato==='disponibile'&&Number(x.quantita)>0)qty[x.variantId]=(qty[x.variantId]||0)+Number(x.quantita);const ricette=applicaTettiIngredienti(all.filter(r=>r.id!==exclude&&r.tipoPortata==='modulare'&&r.sottoCategoriaModulare==='contorno'),state),c=ricette.map(r=>infoVerdura(r,vBy,bBy,qty)).filter(Boolean),seasonal=typeof verdureDiStagione==='function'?verdureDiStagione(new Date(giorno+'T12:00:00')):[];const slot=(pref&&pref._pastoCorrente||'')+'_'+((new Date(giorno+'T00:00:00').getDay()+6)%7),recurring=pref&&pref.verduraRicorrenteVariantId&&(pref.verduraRicorrentePasti||[]).includes(slot)?pref.verduraRicorrenteVariantId:null;const choice=E.chooseVegetable(c,state,{disabledVariantIds:pref&&pref.verdureDisattivate||[],recurringVariantId:recurring,seasonalNames:seasonal});return segnaIngredientiRicetta(choice&&choice.recipe||null,state);}
function ricettaHaCotturaNelNome(name){return /\b(alla piastra|al vapore|al forno|al naturale|al limone|in umido|in padella|alla griglia|grigliat[oaie]|gratinat[oaie]|saltat[oaie]|less[oaie]|bollit[oaie]|sod[oaie]|strapazzat[oaie]|frittata)\b/i.test(name||'');}
function scegliCotturaStandard(subtype,name){if(ricettaHaCotturaNelNome(name)||/prosciutto|bresaola|formagg|mozzarella|ricotta|tonno in scatola/i.test(name||''))return null;const p=COTTURE_PER_PROTEINA_V10[subtype]||['al naturale'];return p[Math.floor(Math.random()*p.length)];}
async function scegliCarboidratoMotore(state,quick){if(!state.carbRemaining)state.carbRemaining=Object.assign({},state.budgetCarb&&state.budgetCarb.residuo||{});if(!state.carbsUsed)state.carbsUsed=state.carboidratiUsati||{};const k=E.chooseCarb(state,CARBOIDRATI_PASTO,{quick:!!quick});state.carboidratiUsati=state.carbsUsed;if(state.budgetCarb)state.budgetCarb.residuo=state.carbRemaining;return k;}
function carbInRecipe(r,carb,vBy){const cfg=CARBOIDRATI_PASTO[carb],target=(cfg&&cfg.ingrediente||'').toLowerCase(),names=(r.ingredienti||[]).map(i=>i.variantId&&vBy.get(i.variantId)?vBy.get(i.variantId).nome.toLowerCase():(i.nomeLibero||'').toLowerCase());return target&&names.includes(target);}
function ricettaDoppioCarboidrato(r,vBy,bBy){let n=0;for(const i of r.ingredienti||[]){const v=vBy.get(i.variantId),b=v&&bBy.get(v.ingredienteId);if(b&&b.gruppo==='carboidrati'&&Number(i.quantita)>=50)n++;}return n>=2;}
async function motoreV10ScegliPrimoReale(carb,state,pref){const [all,vars,bases]=await Promise.all([ricetteAmmesse(true),getAll('varianti'),getAll('ingredienti')]);const vBy=new Map(vars.map(v=>[v.id,v])),bBy=new Map(bases.map(b=>[b.id,b]));let pool=all.filter(r=>(r.tipoPortata||'unico')==='primo'&&carbInRecipe(r,carb,vBy));const simple=pool.filter(r=>!ricettaDoppioCarboidrato(r,vBy,bBy));if(simple.length)pool=simple;pool=applicaTettiIngredienti(pool,state);return segnaIngredientiRicetta(E.chooseRecipe(pool,state,{automatic:true}),state);}
async function motoreV10CarboidratoFattibile(carb){return !!CARBOIDRATI_PASTO[carb];}
function componiNomePrimoModulare(c,s){return c+(s?' '+String(s).replace(/^sugo\s*/i,''):'');}
function componiNomeSecondoModulare(p,c,v){return [p,c,v?'con '+v:''].filter(Boolean).join(' ');}
async function componiPastoModulare(subtype,giorno,excludeSugo,excludeProtein,excludeVeg,quick,pref,state){state=state||await creaStatoMotoreSettimana();pref=pref||{};const protein=await scegliProteinaModulareMotore(subtype,state,excludeProtein);if(!protein)return null;const vars=await getAll('varianti'),vBy=new Map(vars.map(v=>[v.id,v])),hasPotato=carbInRecipe(protein,'patate',vBy);let carb=hasPotato?'patate':(subtype==='affettati'?'pane':await scegliCarboidratoMotore(state,quick));if(subtype==='affettati'&&!hasPotato){state.carbsUsed.pane=(state.carbsUsed.pane||0)+1;if(state.carbRemaining.pane>0)state.carbRemaining.pane--;}const cfg=CARBOIDRATI_PASTO[carb];if(!cfg)return null;let first=hasPotato?null:await motoreV10ScegliPrimoReale(carb,state,pref),sauce=null;if(!hasPotato&&!first&&cfg.haPoolSughi){let sauces=(await cercaComponentiModulari('sugo')).filter(s=>(s.carboidratiCompatibili||[]).includes(carb)&&s.id!==excludeSugo);sauces=applicaTettiIngredienti(sauces,state);sauce=segnaIngredientiRicetta(E.chooseRecipe(sauces,state,{automatic:true,inventoryByVariant:state.inventoryByVariant}),state);}const cov=E.parseCoverage(protein);let veg=null;if(!cov.veg&&!hasPotato)veg=await scegliContornoMotore(giorno,state,pref,excludeVeg);if(!cov.veg&&!hasPotato&&!veg)return null;const cook=scegliCotturaStandard(protein.gruppoProteico,protein.nome);return {primoRicettaRealeId:first&&first.id||null,primoNome:first?null:(hasPotato?null:(sauce?componiNomePrimoModulare(cfg.label,sauce.nome):cfg.label)),primoCarboidrato:carb,primoSugoId:sauce&&sauce.id||null,primoEJolly:!first&&!sauce&&!hasPotato,secondoNome:componiNomeSecondoModulare(protein.nome,cook,veg&&veg.nome),proteinaId:protein.id,cottura:cook,contornoId:veg&&veg.id||null,classe:hasPotato?'unico_completo':'multi'};}
async function generaPortateMotore(giorno,pasto,cella,pref,state){const macro=cella.gruppoProteicoLargo,sub=await scegliSottotipoMotore(macro,state),quick=pasto==='pranzo'?pref.pocoTempoPranzo:pref.pocoTempoCena,meal=await componiPastoModulare(sub,giorno,null,null,null,quick,Object.assign({},pref,{_pastoCorrente:pasto}),state);if(!meal)return {voce:null,errore:`Nessuna combinazione per ${giorno} ${pasto}`};let first=meal.primoRicettaRealeId||null;if(!first&&meal.primoSugoId&&typeof componiPrimoModulare==='function'){const s=await getOne('ricette',meal.primoSugoId),r=s&&await componiPrimoModulare(s,meal.primoCarboidrato);first=r&&r.id||null;}return {voce:{id:giorno+'_'+pasto,modo:'multi',fascia:'facile',porzioni:1,primoId:first,primoCereale:meal.primoCarboidrato,primoSugoId:meal.primoSugoId,secondoId:meal.proteinaId,contornoId:meal.contornoId,cotturaSecondo:meal.cottura,ricettaId:null,categoriaLargaE1:macro,sottotipoProteicoMotore:sub,origineCategoriaMotore:cella.origine,origine:'motore',programmatoIl:new Date().toISOString()},errore:null};}
async function generaPianoSettimana(scarto,opzioni){const days=giorniSettimana(scarto||0),today=todayISO(),pref=Object.assign(await caricaPreferenzeMotoreDaSet(scarto||0),opzioni&&opzioni.preferenze||{}),state=await creaStatoMotoreSettimana(days,{includeAllPlanned:!(opzioni&&opzioni.forza)}),generated=[],errors=[];if(state.nutritionErrors&&state.nutritionErrors.length){const msg=state.nutritionErrors.join(' ');if(typeof avviso==='function')await avviso('Configurazione alimentare non valida: '+msg);return {generati:[],errori:state.nutritionErrors.slice(),griglia:null,nessunGiornoFuturo:false};}const grid=await costruisciGrigliaConfigurata(days,pref.giornoCategoria,state.storico,state.nutritionConfig);const nessunGiornoFuturo=!days.some(d=>E.automaticDayAllowed(d,today));for(const day of days){if(!E.automaticDayAllowed(day,today))continue;state.vegetablesUsedDay=new Set();for(const meal of ['pranzo','cena']){const id=day+'_'+meal,old=await getOne('piano',id);if(old&&(old.consumato||old.bloccata))continue;if(old&&!(opzioni&&opzioni.forza)&&(old.primoId||old.secondoId||old.ricettaId))continue;const result=await generaPortateMotore(day,meal,grid.celle[day][meal],pref,state);if(result.voce){await put('piano',result.voce);generated.push(id);}else errors.push(result.errore);}if(typeof scegliColazioneAutomaticaCoerente==='function'){const id=day+'_colazione';let old=await getOne('piano',id);if(opzioni&&opzioni.forza&&old&&!old.colazioneSpecialeId){old=Object.assign({},old,{componenti:null});}if(!old||(!old.componenti&&!old.colazioneSpecialeId)){const vars=await getAll('varianti');const prefRec=await getOne('impostazioni','colazionePreferita');const giorniRec=await getOne('impostazioni','colazionePreferitaGiorni');const giorniPref=(giorniRec&&giorniRec.valore?giorniRec.valore:[]).map(Number);const idxGiorno=days.indexOf(day);const usaPref=!!(prefRec&&prefRec.valore)&&(giorniPref.length>=7||giorniPref.includes(idxGiorno));let components=null;if(usaPref&&typeof componentiColazioneDaSet==='function'){components=componentiColazioneDaSet(prefRec.valore,vars);}if(!components){const firma=(usaPref&&typeof firmaComponentiColazione==='function'&&typeof componentiColazioneDaSet==='function')?firmaComponentiColazione(componentiColazioneDaSet(prefRec.valore,vars)):null;const escl=await getOne('impostazioni','colazioneIngredientiEsclusi');components=scegliColazioneAutomaticaCoerente(vars,firma?[firma]:[],escl&&escl.valore?escl.valore:[]);}if(components)await put('piano',{id,componenti:components,porzioni:1,origine:'motore',programmatoIl:new Date().toISOString()});}}}if(errors.length&&typeof avviso==='function')await avviso('Menù generato con '+errors.length+' slot non completati.');else if(nessunGiornoFuturo&&typeof avviso==='function')await avviso('Questa settimana non ha giorni futuri da generare: passa alla settimana successiva.');return {generati:generated,errori:errors,griglia:grid,nessunGiornoFuturo};}
async function generaMenuDaConfigSet(scarto){if(typeof mostraVista==='function')mostraVista('menu');const r=await generaPianoSettimana(scarto||0,{forza:true});if(typeof renderMenuSettimanale==='function')await renderMenuSettimanale();if(typeof renderPiano==='function')await renderPiano();return r;}
async function registraRichiestaRicettaReview(d){const r=await getOne('impostazioni','richiesteRicetteReview'),a=r&&Array.isArray(r.valore)?r.valore:[];a.push(Object.assign({id:Date.now().toString(36),creataIl:new Date().toISOString()},d||{}));await put('impostazioni',{chiave:'richiesteRicetteReview',valore:a.slice(-100)});}
async function sviluppaGrigliaCrossWeek(celle){return {celle,errori:[]};}
async function motoreV10CompletaDraftPerRealizzazione(pasto,giorno,draft){if(!draft)return draft;const state=await creaStatoMotoreSettimana(),pref=await caricaPreferenzeMotoreDaSet(0);if(!draft.proteinaId){const sub=draft.sottotipoProposto||risolviSottotipoFine(draft.categoriaLarga||'legumi',{}),r=await scegliProteinaModulareMotore(sub,state,null);if(r){draft.proteinaId=r.id;draft.cottura=scegliCotturaStandard(r.gruppoProteico,r.nome);}}if(!draft.primoCereale)draft.primoCereale=await scegliCarboidratoMotore(state,false);if(!draft.contornoId){const r=await scegliContornoMotore(giorno,state,Object.assign({},pref,{_pastoCorrente:pasto}),null);draft.contornoId=r&&r.id||null;}return draft;}
async function trovaPiattoUnicoCompatibileDraft(pasto,giorno,draft,exclude){const all=await ricetteAmmesse(false),macro=draft.categoriaLarga||motoreCategoriaDiSottotipo(draft.sottotipoProposto),pool=all.filter(r=>r.id!==exclude&&!r.piattoSpeciale&&(r.tipoPortata||'unico')==='unico'&&(!macro||motoreCategoriaDiSottotipo(r.gruppoProteico)===macro));return E.oldest(pool,{},{});}

/* v78 — algebra deterministica di copertura. Le ricette sono unità complete:
   non si deducono sughi/cotture dal nome e si aggiungono soltanto P/C/V mancanti. */
function tokenProteinaMacro(macro){return E.PROTEIN_CODE[motoreCategoriaDiSottotipo(macro)]||null;}
function realizzazione(r){return r?{ricettaId:r.id,copertura:[...E.parseCoverage(r).tokens]}:null;}
async function ricetteDaRealizzazioni(items){const out=[];for(const x of items||[]){const r=x&&x.ricettaId?await getOne('ricette',x.ricettaId):null;if(r&&!out.some(y=>y.id===r.id))out.push(r);}return out;}
function contieneProteineEstranee(r,token){return E.parseCoverage(r).proteinTokens.some(t=>t!==token);}
async function scegliRicettaCopertura(pool,state,exclude){let p=(pool||[]).filter(r=>r&&!r.piattoSpeciale&&r.id!==exclude);p=applicaTettiIngredienti(p,state);return segnaIngredientiRicetta(E.chooseRecipe(p,state,{automatic:true,inventoryByVariant:state.inventoryByVariant}),state);}
async function chiaveCarboRicetta(r){if(!r)return null;const vars=await getAll('varianti'),vBy=new Map(vars.map(v=>[v.id,v]));for(const k of Object.keys(CARBOIDRATI_PASTO))if(carbInRecipe(r,k,vBy))return k;return null;}
async function scegliRiempitivoCarbo(state,quick,exclude){const [all,vars,bases]=await Promise.all([ricetteAmmesse(true),getAll('varianti'),getAll('ingredienti')]),key=await scegliCarboidratoMotore(state,quick),vBy=new Map(vars.map(v=>[v.id,v])),bBy=new Map(bases.map(b=>[b.id,b]));let pool=all.filter(r=>r.id!==exclude&&!r.piattoSpeciale&&E.parseCoverage(r).carb&&!E.parseCoverage(r).proteinTokens.length);if(key){const exact=pool.filter(r=>carbInRecipe(r,key,vBy));if(exact.length)pool=exact;}const singolo=pool.filter(r=>!ricettaDoppioCarboidrato(r,vBy,bBy));if(singolo.length)pool=singolo;const r=await scegliRicettaCopertura(pool,state,exclude);return {ricetta:r,carbKey:(await chiaveCarboRicetta(r))||key};}
async function scegliRiempitivoVerdura(giorno,state,pref,exclude){const r=await scegliContornoMotore(giorno,state,pref||{},exclude);return r&&E.parseCoverage(r).veg?r:null;}
async function completaRealizzazioniCopertura(items,macro,giorno,pasto,state,pref,quick,excludeByRole){
  state=state||await creaStatoMotoreSettimana();pref=pref||{};const token=tokenProteinaMacro(macro),recipes=await ricetteDaRealizzazioni(items),excluded=excludeByRole||{};
  let missing=E.missingCoverage(recipes,macro),carbKey=null;
  if(missing.includes(token)){
    const all=await ricetteAmmesse(true);let pool=all.filter(r=>E.parseCoverage(r).tokens.has(token)&&!contieneProteineEstranee(r,token));
    const sameSubtype=pref.sottotipo?pool.filter(r=>r.gruppoProteico===pref.sottotipo):[];if(sameSubtype.length)pool=sameSubtype;
    if(pref.sottotipo==='affettati'){const withCarb=pool.filter(r=>E.parseCoverage(r).carb);if(withCarb.length)pool=withCarb;}
    const r=await scegliRicettaCopertura(pool,state,excluded.proteina);if(!r)return null;recipes.push(r);missing=E.missingCoverage(recipes,macro);
  }
  if(missing.includes('C')){const c=await scegliRiempitivoCarbo(state,quick,excluded.carb);if(!c.ricetta)return null;recipes.push(c.ricetta);carbKey=c.carbKey;missing=E.missingCoverage(recipes,macro);}
  if(missing.includes('V')){const r=await scegliRiempitivoVerdura(giorno,state,Object.assign({},pref,{_pastoCorrente:pasto}),excluded.contorno);if(!r)return null;recipes.push(r);missing=E.missingCoverage(recipes,macro);}
  if(missing.length)return null;
  const unique=recipes.filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i);
  if(!carbKey){const owner=unique.find(r=>E.parseCoverage(r).carb);carbKey=await chiaveCarboRicetta(owner);}
  segnaFamiglieLimitatePasto(unique,state);
  return {ricette:unique,realizzazioni:unique.map(realizzazione),primoCereale:carbKey};
}
async function componiPastoModulare(subtype,giorno,excludeSugo,excludeProtein,excludeVeg,quick,pref,state){
  state=state||await creaStatoMotoreSettimana();pref=Object.assign({},pref||{},{sottotipo:subtype});const macro=motoreCategoriaDiSottotipo(subtype),x=await completaRealizzazioniCopertura([],macro,giorno,pref._pastoCorrente||'',state,pref,!!quick,{proteina:excludeProtein,contorno:excludeVeg});if(!x)return null;
  const token=tokenProteinaMacro(macro),protein=x.ricette.find(r=>E.parseCoverage(r).tokens.has(token)),carb=x.ricette.find(r=>E.parseCoverage(r).carb),veg=x.ricette.find(r=>E.parseCoverage(r).veg);
  return {realizzazioni:x.realizzazioni,primoRicettaRealeId:carb&&protein&&carb.id===protein.id?null:carb&&carb.id||null,primoCarboidrato:x.primoCereale,primoSugoId:null,primoEJolly:false,proteinaId:protein&&protein.id||null,cottura:null,contornoId:veg&&protein&&veg.id===protein.id?null:veg&&veg.id||null,classe:'copertura'};
}
async function rigeneraComponenteCopertura(realizzazioni,target,macro,giorno,pasto,subtype){
  const token=tokenProteinaMacro(macro),role=target==='proteina'?token:(target==='contorno'?'V':'C'),recipes=await ricetteDaRealizzazioni(realizzazioni),owner=recipes.find(r=>E.parseCoverage(r).tokens.has(role)),kept=recipes.filter(r=>!owner||r.id!==owner.id),state=await creaStatoMotoreSettimana(),pref=Object.assign(await caricaPreferenzeMotoreDaSet(0),{sottotipo:subtype,_pastoCorrente:pasto});
  return completaRealizzazioniCopertura(kept.map(realizzazione),macro,giorno,pasto,state,pref,false,{[target]:owner&&owner.id});
}
async function generaPortateMotore(giorno,pasto,cella,pref,state){const macro=cella.gruppoProteicoLargo,sub=await scegliSottotipoMotore(macro,state),quick=pasto==='pranzo'?pref.pocoTempoPranzo:pref.pocoTempoCena,meal=await componiPastoModulare(sub,giorno,null,null,null,quick,Object.assign({},pref,{_pastoCorrente:pasto}),state);if(!meal)return {voce:null,errore:`Nessuna combinazione completa per ${giorno} ${pasto}`};return {voce:{id:giorno+'_'+pasto,modo:'multi',fascia:'facile',porzioni:1,realizzazioni:meal.realizzazioni,primoId:meal.primoRicettaRealeId,primoCereale:meal.primoCarboidrato,primoSugoId:null,secondoId:meal.proteinaId,contornoId:meal.contornoId,cotturaSecondo:null,ricettaId:null,categoriaLargaE1:macro,sottotipoProteicoMotore:sub,origineCategoriaMotore:cella.origine,origine:'motore',programmatoIl:new Date().toISOString()},errore:null};}
async function motoreV10CompletaDraftPerRealizzazione(pasto,giorno,draft){if(!draft)return draft;const macro=draft.categoriaLarga||motoreCategoriaDiSottotipo(draft.sottotipoProposto)||'legumi',legacy=[draft.proteinaId,draft.primoId,draft.contornoId].filter(Boolean).map(id=>({ricettaId:id})),x=await completaRealizzazioniCopertura(draft.realizzazioni&&draft.realizzazioni.length?draft.realizzazioni:legacy,macro,giorno,pasto,null,{sottotipo:draft.sottotipoProposto,_pastoCorrente:pasto},false,{});if(!x)return draft;draft.realizzazioni=x.realizzazioni;draft.primoCereale=x.primoCereale;const token=tokenProteinaMacro(macro),p=x.ricette.find(r=>E.parseCoverage(r).tokens.has(token)),c=x.ricette.find(r=>E.parseCoverage(r).carb),v=x.ricette.find(r=>E.parseCoverage(r).veg);draft.proteinaId=p&&p.id||null;draft.primoId=c&&p&&c.id===p.id?null:c&&c.id||null;draft.contornoId=v&&p&&v.id===p.id?null:v&&v.id||null;draft.primoSugoId=null;draft.cottura=null;return draft;}
function scegliCotturaStandard(){return null;}
global.FREQUENZE_MOTORE_BIBBIA=FREQUENZE_MOTORE_BIBBIA;global.CAP_SOTTOTIPI_MOTORE=CAP_SOTTOTIPI_MOTORE;global.COTTURE_STANDARD=COTTURE_STANDARD;global.COTTURE_PER_PROTEINA_V10=COTTURE_PER_PROTEINA_V10;
Object.assign(global,{motoreMescola,motoreCategoriaDiSottotipo,costruisciGrigliaBase,validaGrigliaBase,costruisciStoricoConsumatiMotore,scegliMenoRecenteMotore,risolviSottotipoFine,costruisciMappaVarianti,poolDelGiorno,contorniAmmessiPerPool,calcolaPoolVerdureGiornaliero,scegliContornoMotore,caricaPreferenzeMotoreDaSet,caricaConfigurazioneNutrizionaleRisolta,preparaBudgetCarboidratiMotore,creaStatoMotoreSettimana,ricetteAmmesse,registraRichiestaRicettaReview,sviluppaGrigliaCrossWeek,motoreV10CompletaDraftPerRealizzazione,motoreV10ScegliPrimoReale,motoreV10CarboidratoFattibile,filtraContorniPerVerdureAttive,componiPastoModulare,completaRealizzazioniCopertura,rigeneraComponenteCopertura,generaPianoSettimana,generaMenuDaConfigSet,scegliCotturaStandard,trovaPiattoUnicoCompatibileDraft});
global.MOTORE_REGOLE={versione:'79',pipeline:['copertura_proteica','copertura_carboidrato','copertura_verdura'],defaults:E.DEFAULTS};
})(window);
