'use strict';
const assert=require('assert'),fs=require('fs');
const html=fs.readFileSync(require('path').resolve(__dirname,'../index.html'),'utf8');
const has=x=>assert(html.includes(x),`manca: ${x}`),not=x=>assert(!html.includes(x),`residuo vietato: ${x}`);
for(const id of ['view-menu','view-set','view-impostazioni','view-nutrizionista','configAllergeniAttivi','configMacroIngredienti','configVincoliIngredienti','btnApriNutrizionista','btnTornaImpostazioni','btnPulisciCarboidrati','btnCompletaCarboidrati','btnCasualeCarboidrati','btnSalvaCarboidrati','btnPulisciProteine','btnCompletaProteine','btnCasualeProteine','btnSalvaProteine','setCerealiGradimento','btnAnnullaMenu','btnResettaMenu','btnRigeneraMenu','btnSalvaMenu'])has(`id="${id}"`);
not('id="setTettiIngrediente"');not('id="setCercaTettoIngrediente"');not('function renderSetTettiIngrediente');
not("bottoneGiornoAttivo?.scrollIntoView");has("history.scrollRestoration='manual'");
for(const marker of ['vincoliIngredientiNutrizionista','vincoliClassiCarboidrati','nutri-row','data-vincolo-ing'])has(marker);
for(const marker of ['nutri-config-grid','nutri-quantity','#view-nutrizionista{width:100%;min-width:0;overflow-x:hidden;'])has(marker);
not('id="configAvanzataCampi" class="nutri-grid"');not('id="configClassiCarboidrati" class="nutri-grid"');not('id="configVincoliIngredienti" class="nutri-grid"');
for(const marker of ['data-pasto-switch','data-pasto-expander','pasto-contenuto-espandibile','pasto-selettori','data-pasto-imposta'])has(marker);
has('data-componente-editor="carb"');has('aria-pressed=');not('name="ruoloRicerca_${chiaveStato}"');
for(const label of ['🍗 Proteine','🍝 Carboidrato','🥦 Verdure','Cerca ricetta per nome...','Pasto speciale'])has(label);
for(const type of ['data-pasto-refresh="proteina"','data-pasto-refresh="carb"','data-pasto-refresh="contorno"','data-pasto-salvafrigo="proteina"','data-pasto-salvafrigo="contorno"'])has(type);
for(const fn of ['commitMenuDraftAtomico','registraConsumoStorico','mappaStatiDisponibilita','applicaConfigAvanzataRuntime','abilitaRicercaDirettaPasto'])has(`function ${fn}`);
for(const fn of ['nomeConInizialeMaiuscola','calcolaNutrizioneVoceConsumata','nutrizioneCarboidratoModulare'])has(`function ${fn}`);
has("['ricette','ingredienti','varianti'].includes(store)");
has('nutrizioneTotale,');has('if(rec.nutrizioneTotale){aggiungiNutrizione(tot,rec.nutrizioneTotale);continue;}');
has("if(elementId && !haContenutoColazione)");has('const haContenutoSpuntino');has('const haContenutoBlocco');has('if(!haContenutoVoce || !voce.programmatoIl) continue;');
has('window.visualViewport');has("scrollIntoView({block:'center',behavior:'smooth'})");
not("tabAttiva==='portate'");not("tabAttiva==='sfiziosa'");
not('data-pasto-conferma');not('window.location.reload()');has('.slice(0,5)');
has('? primoRicetta.nome');has("sugoRicetta?' · '");not("sugoRicetta?' + '");
console.log('ui-contract: ok');
